const axios = require('axios');
const fs = require('fs');

// Be nice to their API and don't request data any faster than a human user would
const throttleTime = 5000;
const wait = (ms) => new Promise((res) => setTimeout(res, ms));

// These are the API endpoints for all addons for each top-level category
// The idea being we can scrapes all of these addons and create a mega fixture.
// It's likely that some components will be duplicates across categories, but addons
// have primary ids and ember data will de-dupe for us so we're good.
const categories = [
  5, 8, 6, 11, 9, 39, 51, 4, 1, 3, 22, 2, 12, 40, 58, 65, 54, 7, 73, 74, 55, 68,
  62, 60, 56, 79, 53, 29, 10, 13, 59, 61, 63, 64, 66, 67, 70, 71, 75, 76, 77,
  78, 80,
];

async function apiCall(cat) {
  const url = `https://emberobserver.com/api/v2/addons?filter[inCategory]=${cat}&include=categories`;
  console.log(url);
  const t = Date.now();

  try {
    const res = await axios.get(url);
    console.log(`  -> [${res.status}] in ${Date.now() - t}ms`);
    console.log(`  -> ${res.data.data.length} records`);

    return res.data.data;
  } catch (err) {
    console.log('OH NO!!!');
    console.log(err);
  }
}

async function main() {
  let data = [];
  for (let cat of categories) {
    if (cat !== categories[0]) {
      console.log('waiting...');
      await wait(throttleTime);
    }
    const res = await apiCall(cat);
    if (res) data = data.concat(res);
  }

  const json = JSON.stringify({ data }, null, 2);

  const file = `//
// Generated by scrape-api.js script
//
const data = ${json};
export default data;
`;

  console.log('\nWriting file...');
  fs.writeFileSync('app/mocks/fixtures/addons.js', file);
  console.log('Done!');
}

main();
